version: '3.7'
services:
  fastapi:
    container_name: rip
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
      - ./poetry.lock:/opt/pysetup/poetry.lock
      - ./pyproject.toml:/opt/pysetup/pyproject.toml
    ports:
      - 8000:8000
    command: [ "uvicorn", "rip.main:app" , "--reload",  "--host",   "0.0.0.0" ]
  mysql-service:
    container_name: rip_mysql
    image: mysql:8.0
    volumes:
      - database_data_volume:/var/lib/mysql
    environment:
      # .env is loaded automatically
      - MYSQL_ROOT_PASSWORD=422524
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
volumes:
  database_data_volume: