services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: [ "uvicorn", "rip.main:app" , "--reload",  "--host",   "0.0.0.0" ]
  mysql-service:
    image: mysql:8.0
    volumes:
      - database-data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=422524
      - MYSQL_USER=rip_user
      - MYSQL_PASSWORD=rip_pass
      - MYSQL_DATABASE=rip_db
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
volumes:
  database-data-volume:
